{% set name = "panel-material-ui" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panel_material_ui-{{ version }}.tar.gz
  sha256: 313978faad4a76fe73e483ed63a3a774b0ef58d3d8688e6c37bc3a0cf0663802

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - panel >=1.7.0
    - nodejs
    - esbuild
    - packaging
    - pip
  run:
    - python >={{ python_min }}
    - panel >=1.7.0
    - bokeh >=3.7.2
    - packaging

test:
  imports:
    - panel_material_ui
  commands:
    - pip check
  requires:
    - pip

about:
  home: panel-material-ui.holoviz.org
  summary: An extension to bring MaterialUI components to Panel.
  dev_url: https://github.com/panel-extensions/panel-material-ui
  license: BSD-3-Clause
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - philippjfr
    - hoxbro
